### ISSUE TITLE
Remove entry

### ISSUE THREAD

**Issue by devtribe** [chibatching/Kotpref#103]
It's not yet possible to remove an entry from the shared preferences. Would be nice if this works.

**Comment by chibatching** [comment]
We can realize very easily halfway support of this feature.
You can define the extend functions like below.

```kotlin
fun <T> KotprefModel.clear(property: KProperty0<T>) {
    preferences.edit().remove(property.name).apply()
}

// usage
fun main() {
    SomeKotprefModel.remove(SomeKotprefModel::someProperty)
}
```

But this is not complete support, because we can use different string for preferences key name instead of the property name.
To support this case, we have to use `kotlin-reflect` package like LiveData support module. It's a very heavy library to realize this.

```kotlin

fun <T> KotprefModel.clear(property: KProperty0<T>) {
    property.isAccessible = true
    preferences.edit()
        .remove((property.getDelegate() as? PreferenceKey)?.key ?: property.name)
        .apply()
    property.isAccessible = false
}
```

We should consider very carefully introducing this function taking the pros and cons into account.
