### ISSUE TITLE
Kotpref  unitTesting without android context

### ISSUE THREAD

**Issue by jrcacd** [chibatching/Kotpref#130]
We have a lot of code that depends in kotpref.

And we have also many unitTests. 
Majority of them do not use android emulator or context to be as fast as possible.
As is, we can not instantiate kotpref, and so we need to put if's in all place to only see preference's if we are not unit testing so that will not break.

Could kotpref have an boolean option to set it for unit testing = true.
In that option, it only return the setted preference value, but not save it to android preferences?
That would be great!

**Comment by jrcacd** [comment]
Why is this closed?

**Comment by chibatching** [comment]
Sorry for less description.

Because this library deeply depends on SharedPreferences, it is too hard to split the internal process from Android Context and SharedPreferences.
And I think it is enough using Robolectric or mocking library to control its behavior for the test.

Of course, I'm welcome the contribute to realizing it!
