### ISSUE TITLE
How is proguard and code obfuscation solved?

### ISSUE THREAD

**Issue by denebchorny** [chibatching/Kotpref#200]
I mean, if I use the intPref() method, for example, this will take the name of the attribute as the key for the preference.

example: var userId by intPref ()

When applied proguard, this obfuscates the code so that the key instead of being userId could be simply "a" And if I modify the file, it is possible that in the following compilation. I am not sure of this, but I would like to understand if it is so.

**Comment by chibatching** [comment]
Hi,

Kotpref provides consumer proguard rules from https://github.com/chibatching/Kotpref/blob/b7d29e52fced7c3c284ac45421856bc904bdaeab/kotpref/build.gradle#L20

and keep class inherited KotprefModel.
https://github.com/chibatching/Kotpref/blob/b7d29e52fced7c3c284ac45421856bc904bdaeab/kotpref/proguard-rules.pro#L12

However, delegated properties do hard code name of property names in Java compiled class.
So, even if the property name is obfuscated, hardcoded property name is not obfuscated because the obfuscation process is after java compile.
